### PR TITLE
Document setup.

### PR DESCRIPTION
**Pull request by mkcor**
Here we provide all the necessary instructions for serving the dynamic notebook in a slideshow format, using [Voilà](https://github.com/voila-dashboards/voila).

### CODE REVIEW

**Comment by cgusb** [comment]
I was unfamiliar with Mamba so I did some reading up on it including the announcement blog post. Seems like a cool project! I haven't worked with Mamba and didn't already have Conda on my computer so I downloaded the installer from the repo you linked to in `README.md`. I didn't want to add anything to PATH so as to preserve the reference to my current installation of Python, so I created aliases for `conda` and `mamba`. 

Should we include a reference to this in our repo instructions? The installer specifically recommends not adding anything to PATH so likely other people that do not previously have Conda installed might have to do something similar if they still wish to use `conda` and `mamba` commands. Maybe even some kind of brief statement like "If you do not add mambaforge to PATH, you will need to specify the location of each command/executable or set an alias for `conda`/`mamba` commands."

**Comment by cgusb** [comment]
Actually, maybe making an alias was not the way to go. I see that the `solidifcation-tracking` environment was created (I see it when I run the command `$ conda info --envs` and it exists at C:\Users\[user]\mambaforge\envs), but when I try to activate it using `$ conda activate solidification tracking`, `(solidification-tracking) $` is not shown at the beginning of the command prompt and `$ conda info --envs` shows me still in the base environment. Any ideas for how to proceed?

**Comment by mkcor** [comment]
I don't think we should enter into the details, because setting up a reproducible scientific computing environment is a very broad topic (it's not specific to this project). I added 89ad0c4 so people can guess that Mambaforge is comparable to Miniconda, which is well-established. Then they can follow the links to dig deeper.

You don't need aliases indeed; if you install Mambaforge as a user in your root directory, plus you didn't have any previous Conda installed, clearly there is no other place your system can look for when you run mamba/conda commands.

**Comment by cgusb** [comment]
Okay sounds good! I will merge this now and try to do that.

**Pull request merged**
